name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Run tests
        run: yarn test
